# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 14:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(default=datetime.datetime.now)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_finalizacion', models.DateTimeField()),
                ('carpeta', models.CharField(max_length=20)),
                ('database', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('nif', models.CharField(max_length=11)),
                ('direccion', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('fecha_alta', models.DateTimeField(default=datetime.datetime.now)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(default=datetime.datetime.now)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_finalizacion', models.DateTimeField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenSociety.App')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenSociety.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(default=datetime.datetime.now)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_finalizacion', models.DateTimeField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenSociety.App')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=55)),
                ('desc', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='plugin',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenSociety.Producto'),
        ),
        migrations.AddField(
            model_name='historial',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenSociety.Producto'),
        ),
        migrations.AddField(
            model_name='app',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenSociety.Cliente'),
        ),
        migrations.AddField(
            model_name='app',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenSociety.Producto'),
        ),
    ]
