# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 12:50
from __future__ import unicode_literals

import builtins
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpenSociety', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(default=datetime.datetime.now)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_finalizacion', models.DateTimeField()),
                ('carpeta', models.CharField(max_length=20)),
                ('database', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenSociety.Cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenSociety.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(default=datetime.datetime.now)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_finalizacion', models.DateTimeField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenSociety.App')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenSociety.Cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenSociety.Producto')),
            ],
        ),
        migrations.RemoveField(
            model_name='compra',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='producto',
        ),
        migrations.AddField(
            model_name='historial',
            name='fecha_finalizacion',
            field=models.DateTimeField(default=builtins.id),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.AddField(
            model_name='historial',
            name='app',
            field=models.ForeignKey(default=builtins.id, on_delete=django.db.models.deletion.CASCADE, to='OpenSociety.App'),
            preserve_default=False,
        ),
    ]
