# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AsociacionVirtual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.ForeignKey(default='01/01/2000', on_delete=django.db.models.deletion.CASCADE, related_name='fecha', to='AsociacionVirtual.Stock')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombre', to='AsociacionVirtual.Stock')),
                ('precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coste', to='AsociacionVirtual.Stock')),
            ],
        ),
        migrations.AlterField(
            model_name='socio',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
