# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 12:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsociacionVirtual', '0002_auto_20160502_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=30)),
                ('fecha_alta', models.DateTimeField(default=datetime.datetime.now)),
                ('telefono', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
    ]
